### ISSUE TITLE
Remove brand css colors from theme code

### ISSUE THREAD

**Issue by nicholemaureen** [oomphinc/scss-scaffold#14]
Running into issues where there's no 'dark', 'green', etc.

**Comment by johncionci** [comment]
Could you elaborate?

**Comment by nicholemaureen** [comment]
The code element calls for " palette('brand', 'green') ", for example, but I haven't set a green in the brand palette because it doesn't apply. So I got some lame errors. Just going to generalize calls to brand colors to avoid that.

**Comment by johncionci** [comment]
Two things I can think of, 1. it maybe an error calling the function palette(s) or color(s) from when I changed it and it got changed back, 2. could be from when J changed the color defaults and forgot to replace the function call with one of the new default colors.

**Comment by johncionci** [comment]
@nichole, ran into the same error.

If you delete green from your brand palette it will throw an error because green is being called in _typography.scss in two places.
<img width="626" alt="screen shot 2016-06-16 at 1 06 25 pm" src="https://cloud.githubusercontent.com/assets/1957330/16125834/5d055bb8-33c3-11e6-952f-f136e85e87bf.png">

**Comment by jhogue** [comment]
Yeah, hmmm. Base typography rules require a color for `code` elements and `pre` tags. We can either declare it as a mono color for our base, or, keep a green in a "system" palette. I can think most sites need a red, yellow and green color for elements like warnings, errors, and in this case, code. We can then change those colors on a project by project basis.

**Comment by jhogue** [comment]
Fixing this with a new PR.
